[applications]

firefox = ""
neovide = ""
Code = ""
Chromium = ""
gthumb = ""
swappy = ""
"org.twosheds.iwgtk" = "直"
"org.gnome.Weather" = ""
"org.kde.krusader" = ""
albert = ""
gnome_system_monitor = ""